### ISSUE TITLE
Investigate maintenance for avoiding `<linux/kvm.h>'

### ISSUE THREAD

**Issue by kitschysynq** [kitschysynq/darity#5]
If we can get along with maintaining the constants and structs directly in Go, it should be possible to avoid using cgo at all. (see #4) Before we get too deep into that, it would be nice to take a look at how often they change, and how much maintenance work would be required.

**Comment by mdlayher** [comment]
From my understanding, these values cannot change unless `KVM_API_VERSION` changes, in which case, `New()` will return an error:

```
/*
 * Userspace interface for /dev/kvm - kernel based virtual machine
 *
 * Note: you must update KVM_API_VERSION if you change this interface.
 */

#include <linux/types.h>

#include <linux/ioctl.h>
#include <asm/kvm.h>

#define KVM_API_VERSION 12
```

**Comment by kitschysynq** [comment]
Well, then. Investigation... complete.  We'll just add the values and structs by hand as we need/implement them?

**Comment by mdlayher** [comment]
That's my understanding.  The structs might get a little more complicated if there are union types present, but we should be able to do most of it in pure Go, I believe.

**Comment by kitschysynq** [comment]
As long as we don't have to do code generation to get around cgo (which amounts to the same thing, more or less), or do a bunch of leg work to keep up with these, I'm satisfied.
